version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/app
      - ./docker/nginx/default.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - default
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/app
    environment:
      PHP_IDE_CONFIG: 'serverName=docker'

networks:
  default:
    driver: bridge